### ISSUE TITLE
Examples with this library

### ISSUE THREAD

**Issue by frideosapps** [frideosapps/frideos_flutter#6]
If you would like to contribute with examples built with this library it would be really appreciated.

**Comment by AlexandreRoba** [comment]
Hi @frideosapps I started porting the https://fluttersamples.com/ with the frideos package but stopped when starting using the v4 and the StreamedObject Interface breaking change. I believe we should have a talk on this. Have some time somewhen?

**Comment by frideosapps** [comment]
I am sorry for this inconvenience, but when you gave me that advice on twitter I accepted it and started to work on a port of the Todo app, currently there is a PR. You can take a look at the example [here](https://github.com/frideosapps/flutter_architecture_samples/tree/frideos_library/frideos_library). I tried to take advantage of all the features of the package mantaining the sample as simple as possible.

**Comment by AlexandreRoba** [comment]
This is great news. Good to see you have done it :)
